LeftAndMain:
  extensions:
    - 'StudioBonito\SilverStripe\TypeKit\Extensions\LeftAndMainRequirementsExtension'
SiteConfig:
  extensions:
    - 'StudioBonito\SilverStripe\TypeKit\Extensions\TypeKitSiteConfigExtension'